### ISSUE TITLE
搭在龟壳上容器会无限重启

### ISSUE THREAD

**Issue by TurboJerry** [chiupam/Docker#3]
佬,请问我搭在本地计算机上可正常运行,搭在龟壳上容器会无限重启,是还需要配置java环境吗?

![image](https://user-images.githubusercontent.com/77106760/183002142-7f9e2832-6788-45e9-a082-bcb7a3eadf4b.png)

**Comment by chiupam** [comment]
不用 只要有docker就行 但我有试过arm64机器会无限重启 建议用amd64机器再试试

发自我的iPhone

**Comment by TurboJerry** [comment]
> 不用 只要有docker就行 但我有试过arm64机器会无限重启 建议用amd64机器再试试 发自我的iPhone
> […](#)
> 在 2022年8月5日，12:38，TurboJerry ***@***.***> 写道： ﻿ 佬,请问我搭在本地计算机上可正常运行,搭在龟壳上容器会无限重启,是还需要配置java环境吗? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.

还真是哎,用AMD就行了,谢谢佬
