### ISSUE TITLE
这个项目还能使用吗？

### ISSUE THREAD

**Issue by jinshuqishi2019** [chiupam/Docker#6]
根据说明搭建了一个docker，使用demo.py运行的结果如下
```
{'msg': '参数异常', 'code': 500}
{'msg': '参数异常', 'code': 500}
```
多次修改参数，还是一样的结果，不知是我写错了，还是这个api停止服务，麻烦作者解答，谢谢。

**Comment by chiupam** [comment]
![image](https://user-images.githubusercontent.com/65508083/188705667-a96ee4cd-d061-436e-831c-a7b2eb3c0227.png)
建议先检查自己写的 demo.py 文件

**Comment by chiupam** [comment]
![image](https://user-images.githubusercontent.com/65508083/188705874-6763e4c2-cb5e-4e80-9c19-9057a75ff9a9.png)

**Comment by jinshuqishi2019** [comment]
谢谢大佬解答
